//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Pokémon Location.
        /// </summary>
        public static string AddPokemonLocaiton {
            get {
                return ResourceManager.GetString("AddPokemonLocaiton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a fan website, we are in no way affiliated with Niantic Inc, Pokémon Inc, Nintendo Inc, Creatures Inc, or GAME FREAK inc..
        /// </summary>
        public static string Affiliated {
            get {
                return ResourceManager.GetString("Affiliated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Pokémon.
        /// </summary>
        public static string AllPokemon {
            get {
                return ResourceManager.GetString("AllPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click and hold on the map to add a Pokémon location!.
        /// </summary>
        public static string ClickToAdd {
            get {
                return ResourceManager.GetString("ClickToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you see this {0} here too?.
        /// </summary>
        public static string DidYouSeeThisHere {
            get {
                return ResourceManager.GetString("DidYouSeeThisHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live mode will show only pokemon sighted in the last 15 minutes..
        /// </summary>
        public static string LiveModeInfo {
            get {
                return ResourceManager.GetString("LiveModeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live mode: OFF.
        /// </summary>
        public static string LiveModeOff {
            get {
                return ResourceManager.GetString("LiveModeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live mode: ON.
        /// </summary>
        public static string LiveModeOn {
            get {
                return ResourceManager.GetString("LiveModeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (MM/DD/YYYY).
        /// </summary>
        public static string MMDDYYYY {
            get {
                return ResourceManager.GetString("MMDDYYYY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} other did!.
        /// </summary>
        public static string OtherDid {
            get {
                return ResourceManager.GetString("OtherDid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} others did too!.
        /// </summary>
        public static string OthersDid {
            get {
                return ResourceManager.GetString("OthersDid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click on the map to add a sighting..
        /// </summary>
        public static string RightClickToAdd {
            get {
                return ResourceManager.GetString("RightClickToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Pokémon.
        /// </summary>
        public static string SelectPokemon {
            get {
                return ResourceManager.GetString("SelectPokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Found.
        /// </summary>
        public static string TimeFound {
            get {
                return ResourceManager.GetString("TimeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to PikaMaps, the most extensive database of verified Pokémon sightings!.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
